# Generated by Django 4.1.7 on 2023-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(primary_key=13, serialize=False),
        ),
    ]
