# Generated by Django 4.1.7 on 2023-02-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_marks_student_delete_contact_marks_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='roll_no',
            new_name='id_rollno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='id_rollno',
        ),
    ]
