# Generated by Django 4.1.7 on 2023-02-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_remove_marks_id_rollno_marks_id_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='biology',
            new_name='computer',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='physics',
            new_name='maths',
        ),
    ]
