# Generated by Django 4.1.7 on 2023-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_remove_contact_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=20)),
                ('cus_email', models.EmailField(max_length=254)),
                ('cus_phone', models.IntegerField()),
            ],
        ),
    ]
